app = "digjourney"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[http_service]
  internal_port = 8080
  force_https = true
