app = "digjourney"
primary_region = "fra"

[env]
  NODE_ENV = "production"

[build.args]
  NODE_ENV = "production"

[build]
  builder = "paketobuildpacks/builder-jammy-base"
  buildpacks = ["paketo-buildpacks/nodejs"]

[http_service]
  internal_port = 8080
  force_https = true
